apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-devops-backend
  labels:
    app: task-devops-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-devops-backend
  template:
    metadata:
      labels:
        app: task-devops-backend
    spec:
      containers:
        - name: task-devops-backend
          image: pwill12/task-devops-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
            - name: PORT
              value: "8000"
            - name: NODE_ENV
              value: 'production'
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
