apiVersion: v1
kind: Service
metadata:
  name: task-devops-backend-service
  labels:
    app: task-devops-backend
spec:
  selector:
    app: task-devops-backend
  ports:
    - protocol: TCP
      port: 8000 # Service port
      targetPort: 8000 # Container port
  type: NodePort # change to LoadBalancer if running in cloud